// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Aenea.Cli")>]
[<assembly: AssemblyProductAttribute("Aenea")>]
[<assembly: AssemblyDescriptionAttribute("")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Aenea.Cli"
    let [<Literal>] AssemblyProduct = "Aenea"
    let [<Literal>] AssemblyDescription = ""
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
